#!/bin/bash
#chkconfig: 345 99 90
#description: hdqnwxeb server
#processname: hdqnwxeb
HDQNWXWEB_HOME=/root/hdqn-wxweb
export FLASK_CONFIG=production
case $1 in
    start)su root $HDQNWXWEB_HOME/bin/hdqnwxweb.sh start;;
    stop)su root $HDQNWXWEB_HOME/bin/hdqnwxweb.sh stop;;
    restart)su root $HDQNWXWEB_HOME/bin/hdqnwxweb.sh restart;;
    *)echo "require start|stop|restart";;
esac