"""empty message

Revision ID: 79129d6fa01d
Revises: 
Create Date: 2019-03-11 03:30:46.464171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79129d6fa01d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('imagematerials', 'media_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('musicmaterials', 'description',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('musicmaterials', 'hqmusic_url',
               existing_type=mysql.VARCHAR(length=2000),
               nullable=False)
    op.alter_column('musicmaterials', 'music_url',
               existing_type=mysql.VARCHAR(length=2000),
               nullable=False)
    op.alter_column('musicmaterials', 'title',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
    op.alter_column('newsmaterials', 'description',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('newsmaterials', 'pic_url',
               existing_type=mysql.VARCHAR(length=2000),
               nullable=False)
    op.alter_column('newsmaterials', 'title',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
    op.alter_column('newsmaterials', 'url',
               existing_type=mysql.VARCHAR(length=2000),
               nullable=False)
    op.alter_column('textmaterials', 'content',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('videomaterials', 'description',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('videomaterials', 'media_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('videomaterials', 'title',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
    op.alter_column('voicematerials', 'media_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('voicematerials', 'media_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('videomaterials', 'title',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    op.alter_column('videomaterials', 'media_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('videomaterials', 'description',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('textmaterials', 'content',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('newsmaterials', 'url',
               existing_type=mysql.VARCHAR(length=2000),
               nullable=True)
    op.alter_column('newsmaterials', 'title',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    op.alter_column('newsmaterials', 'pic_url',
               existing_type=mysql.VARCHAR(length=2000),
               nullable=True)
    op.alter_column('newsmaterials', 'description',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('musicmaterials', 'title',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    op.alter_column('musicmaterials', 'music_url',
               existing_type=mysql.VARCHAR(length=2000),
               nullable=True)
    op.alter_column('musicmaterials', 'hqmusic_url',
               existing_type=mysql.VARCHAR(length=2000),
               nullable=True)
    op.alter_column('musicmaterials', 'description',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('imagematerials', 'media_id',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
